// Auto-Generated by FAKE; do not edit
namespace System
open System.Reflection

[<assembly: AssemblyTitleAttribute("Uhura")>]
[<assembly: AssemblyProductAttribute("Uhura")>]
[<assembly: AssemblyDescriptionAttribute("Fast routing library for owin")>]
[<assembly: AssemblyVersionAttribute("1.0")>]
[<assembly: AssemblyFileVersionAttribute("1.0")>]
[<assembly: AssemblyConfigurationAttribute("Release")>]
do ()

module internal AssemblyVersionInformation =
    let [<Literal>] AssemblyTitle = "Uhura"
    let [<Literal>] AssemblyProduct = "Uhura"
    let [<Literal>] AssemblyDescription = "Fast routing library for owin"
    let [<Literal>] AssemblyVersion = "1.0"
    let [<Literal>] AssemblyFileVersion = "1.0"
    let [<Literal>] AssemblyConfiguration = "Release"
